#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : dkms
Version  : 2.6.1
Release  : 1
URL      : https://github.com/dell/dkms/archive/v2.6.1.tar.gz
Source0  : https://github.com/dell/dkms/archive/v2.6.1.tar.gz
Summary  : megaraid2 dkms package
Group    : Development/Tools
License  : GPL-2.0 GPL-2.0+
Requires: dkms-bin = %{version}-%{release}
Requires: dkms-license = %{version}-%{release}
Requires: dkms-man = %{version}-%{release}

%description
Kernel modules for %{module_name} %{version} in a DKMS wrapper.

%package bin
Summary: bin components for the dkms package.
Group: Binaries
Requires: dkms-license = %{version}-%{release}
Requires: dkms-man = %{version}-%{release}

%description bin
bin components for the dkms package.


%package license
Summary: license components for the dkms package.
Group: Default

%description license
license components for the dkms package.


%package man
Summary: man components for the dkms package.
Group: Default

%description man
man components for the dkms package.


%prep
%setup -q -n dkms-2.6.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1547578170
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1547578170
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/dkms
cp COPYING %{buildroot}/usr/share/package-licenses/dkms/COPYING
cp debian/copyright %{buildroot}/usr/share/package-licenses/dkms/debian_copyright
%make_install

%files
%defattr(-,root,root,-)
%exclude /var/lib/dkms/dkms_dbversion
/usr/lib/dkms/common.postinst
/usr/lib/dkms/dkms_autoinstaller

%files bin
%defattr(-,root,root,-)
/usr/bin/dkms

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/dkms/COPYING
/usr/share/package-licenses/dkms/debian_copyright

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man8/dkms.8.gz
